# Set variable names and paths
base_path = "./"
project_folders = [
    "analysis",
    "data",
    "data/reference_sequences",
    "data/reads",
    "bin",
    "notes",
]
reademption_exe = "reademption"
reademption_main_folder = "READemption_analysis"
reademption_main_folder_path = f"./analysis/{reademption_main_folder}"
ftp_source = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/210/855/GCF_000210855.2_ASM21085v2"
salmonella_genome_path = f"{base_path}data/reference_sequences/salmonella.fa.gz"
reademption_ref_seq_folder = (
    f"{reademption_main_folder_path}/input/reference_sequences"
)
reads_folder_path = f"{base_path}data/reads"
reademption_reads_folder = f"{reademption_main_folder_path}/input/reads"
mapping_processes = 6


rule install_reademption:
	shell: "sudo pip3 install READemption"

rule create_folders:
	run:
		import os 
		for folder in project_folders:
				full_path = base_path + folder
				if not os.path.exists(full_path):
				    print(f"Creating folder {full_path}")
				    os.mkdir(full_path)

rule create_reademption_project_folders:
	run: 
		os.system(f"{reademption_exe} create -f {reademption_main_folder_path}")

rule download_and_unzip_reference_sequences:
	run:
		import os
    		os.system(
        		f"wget -O {salmonella_genome_path} "
        		f"{ftp_source}/GCF_000210855.2_ASM21085v2_genomic.fna.gz"
    		)
		os.system(f"gunzip {salmonella_genome_path}")

rule link_reference_sequence:
	run:
		salmonella_genome_path_unpacked = salmonella_genome_path.rsplit(".gz")[0]
    		salmonella_genome = os.path.basename(salmonella_genome_path_unpacked)
    		print(f"Linking {salmonella_genome} to {reademption_ref_seq_folder}")
    		os.system(
        		f"ln -s ../../../../data/reference_sequences/{salmonella_genome} {reademption_ref_seq_folder}"
			)

rule download_reads:
	run:
		base_url = "http://reademptiondata.imib-zinf.net/"
		read_files = [
			"InSPI2_R1.fa.bz2",
			"InSPI2_R2.fa.bz2",
			"LSP_R1.fa.bz2",
			"LSP_R2.fa.bz2"
		]
		for read_file in read_files:
			os.system(f"wget -P {reads_folder_path} {base_url}{read_file}")

rule link_reads:
	run:
		import os
		import glob
		read_files = glob.glob(f"{reads_folder_path}/*fa.bz2")
		for read_file_path in read_files:
			print(f"linking {read_file_path} to {reademption_reads_folder}")
			read_file = os.path.basename(read_file_path)
			os.system(
				f"ln -s ../../../../data/reads/{read_file} {reademption_reads_folder}"
			)
rule align_reads:
	run:
               os.system(
                       f"{reademption_exe} align "
                       f"-p {mapping_processes} "
                       "-a 95 "
                       "-l 20 "
                       "--poly_a_clipping "
                       "--progress "
                       "--split "
                       f"-f {reademption_main_folder_path}"
               )

